{{- if not .Values.backend.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rancher-hub.backend.fullname" . }}
  labels:
    {{- include "rancher-hub.backend.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.backend.secrets.jwtSecret | default (randAlphaNum 32) | b64enc | quote }}
  {{- if .Values.postgresql.enabled }}
  database-password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else if .Values.backend.env.database.password }}
  database-password: {{ .Values.backend.env.database.password | b64enc | quote }}
  {{- end }}
{{- end }}
