{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rancher-hub.postgresql.fullname" . }}
  labels:
    {{- include "rancher-hub.postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
{{- end }}
